write_queries:
  description: >
    Plan what data you need to gather to analyze pick frequency and item affinity trends. You are trying to highlight specific trends for that business.
    Then, review the database description and write efficient SQL queries to gather that data. 
    The database description is provided in {queries}.
  expected_output: >
    The SQL queries to be executed.
  agent: query_writer

review_and_execute_queries:
  description: >
    For each query from the query_writer:
    - Review for cost and efficiency.
    - Optimize if necessary.
    - Execute using MySQLQueryTool.
  expected_output: > 
    The executed queries and their results.
  agent: query_reviewer

document_results:
  description: >
    Use the results of the queries to investigate pick frequency and item affinity trends, and create a clear and informative report with your findings.
    The report should be as specific as possible to the business and their needs.
  expected_output: >
    A Markdown-formatted report suitable for both technical and non-technical audiences.
  agent: data_analyst
