write_queries:
  description: Using {trends} and database details in {queries}, write efficient SQL queries to investigate and understand the specified trends.
  expected_output: >  
    The SQL queries to be executed.
  agent: query_writer

review_and_execute_queries:
  description: >
    For each query from the query_writer:
    - Review for cost and efficiency.
    - Optimize if necessary.
    - Execute using MySQLQueryTool.
  expected_output: > 
    The executed queries and their results.
  agent: query_reviewer

document_results:
  description: Review the query results, the trends to investigate in {trends}, and create a clear and informative report.
  expected_output: A Markdown-formatted report suitable for both technical and non-technical audiences.
  agent: data_analyst
